#
# Copyright © Inflowmatix Limited 2020-2023
# Copyright © arboricity™ 2020-2023
#
name: Elixir Standard CI Build and Testing

on:
  workflow_call:
    secrets:
      HEX_API_KEY:
        required: true

env:
  MIX_ENV: test

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.14.4]
        otp: [24.3.4]

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@c2e02f777c158310fc6d3d4e11b36a52d2d52db8 # v1.15.4
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: mix-cache #id to use in retrieve action
        with:
          path: deps
          key: mix-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix hex.organization auth inflowmatix --key "$HEX_API_KEY"
          mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Run Tests
        env:
          CONGRUITY_API_URL: "https://localhost:8443/v1"
        run: |
          mix test

      - name: Retrieve PLT Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: plt-cache
        with:
          path: priv/plts
          key: plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt

      - name: Run dialyzer
        run: mix dialyzer --no-check
